#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGEats.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CheckPostingDB")]
	public partial class DBGGEatsAppDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEXTENSION_DATA_VALUE(EXTENSION_DATA_VALUE instance);
    partial void UpdateEXTENSION_DATA_VALUE(EXTENSION_DATA_VALUE instance);
    partial void DeleteEXTENSION_DATA_VALUE(EXTENSION_DATA_VALUE instance);
    partial void InsertEXTENSION_DATA_PROPERTY(EXTENSION_DATA_PROPERTY instance);
    partial void UpdateEXTENSION_DATA_PROPERTY(EXTENSION_DATA_PROPERTY instance);
    partial void DeleteEXTENSION_DATA_PROPERTY(EXTENSION_DATA_PROPERTY instance);
    partial void InsertMENU_ITEM_MASTER(MENU_ITEM_MASTER instance);
    partial void UpdateMENU_ITEM_MASTER(MENU_ITEM_MASTER instance);
    partial void DeleteMENU_ITEM_MASTER(MENU_ITEM_MASTER instance);
    #endregion
		
		public DBGGEatsAppDataContext() : 
				base(global::GGEats.Data.Properties.Settings.Default.CheckPostingDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBGGEatsAppDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBGGEatsAppDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBGGEatsAppDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBGGEatsAppDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EXTENSION_DATA_VALUE> EXTENSION_DATA_VALUEs
		{
			get
			{
				return this.GetTable<EXTENSION_DATA_VALUE>();
			}
		}
		
		public System.Data.Linq.Table<EXTENSION_DATA_PROPERTY> EXTENSION_DATA_PROPERTies
		{
			get
			{
				return this.GetTable<EXTENSION_DATA_PROPERTY>();
			}
		}
		
		public System.Data.Linq.Table<MENU_ITEM_MASTER> MENU_ITEM_MASTERs
		{
			get
			{
				return this.GetTable<MENU_ITEM_MASTER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EXTENSION_DATA_VALUE")]
	public partial class EXTENSION_DATA_VALUE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ExtensionDataValueID;
		
		private long _DataElementID;
		
		private string _XMLProperties;
		
		private long _ExtensionDataPropertyID;
		
		private long _HierStrucID;
		
		private int _LANGID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExtensionDataValueIDChanging(long value);
    partial void OnExtensionDataValueIDChanged();
    partial void OnDataElementIDChanging(long value);
    partial void OnDataElementIDChanged();
    partial void OnXMLPropertiesChanging(string value);
    partial void OnXMLPropertiesChanged();
    partial void OnExtensionDataPropertyIDChanging(long value);
    partial void OnExtensionDataPropertyIDChanged();
    partial void OnHierStrucIDChanging(long value);
    partial void OnHierStrucIDChanged();
    partial void OnLANGIDChanging(int value);
    partial void OnLANGIDChanged();
    #endregion
		
		public EXTENSION_DATA_VALUE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtensionDataValueID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ExtensionDataValueID
		{
			get
			{
				return this._ExtensionDataValueID;
			}
			set
			{
				if ((this._ExtensionDataValueID != value))
				{
					this.OnExtensionDataValueIDChanging(value);
					this.SendPropertyChanging();
					this._ExtensionDataValueID = value;
					this.SendPropertyChanged("ExtensionDataValueID");
					this.OnExtensionDataValueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataElementID", DbType="BigInt NOT NULL")]
		public long DataElementID
		{
			get
			{
				return this._DataElementID;
			}
			set
			{
				if ((this._DataElementID != value))
				{
					this.OnDataElementIDChanging(value);
					this.SendPropertyChanging();
					this._DataElementID = value;
					this.SendPropertyChanged("DataElementID");
					this.OnDataElementIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XMLProperties", DbType="NVarChar(MAX)")]
		public string XMLProperties
		{
			get
			{
				return this._XMLProperties;
			}
			set
			{
				if ((this._XMLProperties != value))
				{
					this.OnXMLPropertiesChanging(value);
					this.SendPropertyChanging();
					this._XMLProperties = value;
					this.SendPropertyChanged("XMLProperties");
					this.OnXMLPropertiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtensionDataPropertyID", DbType="BigInt NOT NULL")]
		public long ExtensionDataPropertyID
		{
			get
			{
				return this._ExtensionDataPropertyID;
			}
			set
			{
				if ((this._ExtensionDataPropertyID != value))
				{
					this.OnExtensionDataPropertyIDChanging(value);
					this.SendPropertyChanging();
					this._ExtensionDataPropertyID = value;
					this.SendPropertyChanged("ExtensionDataPropertyID");
					this.OnExtensionDataPropertyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HierStrucID", DbType="BigInt NOT NULL")]
		public long HierStrucID
		{
			get
			{
				return this._HierStrucID;
			}
			set
			{
				if ((this._HierStrucID != value))
				{
					this.OnHierStrucIDChanging(value);
					this.SendPropertyChanging();
					this._HierStrucID = value;
					this.SendPropertyChanged("HierStrucID");
					this.OnHierStrucIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANGID", DbType="Int NOT NULL")]
		public int LANGID
		{
			get
			{
				return this._LANGID;
			}
			set
			{
				if ((this._LANGID != value))
				{
					this.OnLANGIDChanging(value);
					this.SendPropertyChanging();
					this._LANGID = value;
					this.SendPropertyChanged("LANGID");
					this.OnLANGIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EXTENSION_DATA_PROPERTY")]
	public partial class EXTENSION_DATA_PROPERTY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ExtensionDataPropertyID;
		
		private string _Name;
		
		private int _DbTableID;
		
		private System.Nullable<int> _ValueType;
		
		private string _ValueLimits;
		
		private System.Nullable<int> _SortPriority;
		
		private System.Nullable<int> _DisplayWidth;
		
		private System.Nullable<long> _DisplayNameID;
		
		private bool _IsEditable;
		
		private bool _IsViewable;
		
		private System.Nullable<long> _CommentID;
		
		private bool _IsDownloadable;
		
		private long _HierStrucID;
		
		private System.Nullable<int> _ObjectNumber;
		
		private string _APPLICATIONTYPE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExtensionDataPropertyIDChanging(long value);
    partial void OnExtensionDataPropertyIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDbTableIDChanging(int value);
    partial void OnDbTableIDChanged();
    partial void OnValueTypeChanging(System.Nullable<int> value);
    partial void OnValueTypeChanged();
    partial void OnValueLimitsChanging(string value);
    partial void OnValueLimitsChanged();
    partial void OnSortPriorityChanging(System.Nullable<int> value);
    partial void OnSortPriorityChanged();
    partial void OnDisplayWidthChanging(System.Nullable<int> value);
    partial void OnDisplayWidthChanged();
    partial void OnDisplayNameIDChanging(System.Nullable<long> value);
    partial void OnDisplayNameIDChanged();
    partial void OnIsEditableChanging(bool value);
    partial void OnIsEditableChanged();
    partial void OnIsViewableChanging(bool value);
    partial void OnIsViewableChanged();
    partial void OnCommentIDChanging(System.Nullable<long> value);
    partial void OnCommentIDChanged();
    partial void OnIsDownloadableChanging(bool value);
    partial void OnIsDownloadableChanged();
    partial void OnHierStrucIDChanging(long value);
    partial void OnHierStrucIDChanged();
    partial void OnObjectNumberChanging(System.Nullable<int> value);
    partial void OnObjectNumberChanged();
    partial void OnAPPLICATIONTYPEChanging(string value);
    partial void OnAPPLICATIONTYPEChanged();
    #endregion
		
		public EXTENSION_DATA_PROPERTY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtensionDataPropertyID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ExtensionDataPropertyID
		{
			get
			{
				return this._ExtensionDataPropertyID;
			}
			set
			{
				if ((this._ExtensionDataPropertyID != value))
				{
					this.OnExtensionDataPropertyIDChanging(value);
					this.SendPropertyChanging();
					this._ExtensionDataPropertyID = value;
					this.SendPropertyChanged("ExtensionDataPropertyID");
					this.OnExtensionDataPropertyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(1024) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DbTableID", DbType="Int NOT NULL")]
		public int DbTableID
		{
			get
			{
				return this._DbTableID;
			}
			set
			{
				if ((this._DbTableID != value))
				{
					this.OnDbTableIDChanging(value);
					this.SendPropertyChanging();
					this._DbTableID = value;
					this.SendPropertyChanged("DbTableID");
					this.OnDbTableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueType", DbType="Int")]
		public System.Nullable<int> ValueType
		{
			get
			{
				return this._ValueType;
			}
			set
			{
				if ((this._ValueType != value))
				{
					this.OnValueTypeChanging(value);
					this.SendPropertyChanging();
					this._ValueType = value;
					this.SendPropertyChanged("ValueType");
					this.OnValueTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueLimits", DbType="NVarChar(MAX)")]
		public string ValueLimits
		{
			get
			{
				return this._ValueLimits;
			}
			set
			{
				if ((this._ValueLimits != value))
				{
					this.OnValueLimitsChanging(value);
					this.SendPropertyChanging();
					this._ValueLimits = value;
					this.SendPropertyChanged("ValueLimits");
					this.OnValueLimitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortPriority", DbType="Int")]
		public System.Nullable<int> SortPriority
		{
			get
			{
				return this._SortPriority;
			}
			set
			{
				if ((this._SortPriority != value))
				{
					this.OnSortPriorityChanging(value);
					this.SendPropertyChanging();
					this._SortPriority = value;
					this.SendPropertyChanged("SortPriority");
					this.OnSortPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayWidth", DbType="Int")]
		public System.Nullable<int> DisplayWidth
		{
			get
			{
				return this._DisplayWidth;
			}
			set
			{
				if ((this._DisplayWidth != value))
				{
					this.OnDisplayWidthChanging(value);
					this.SendPropertyChanging();
					this._DisplayWidth = value;
					this.SendPropertyChanged("DisplayWidth");
					this.OnDisplayWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayNameID", DbType="BigInt")]
		public System.Nullable<long> DisplayNameID
		{
			get
			{
				return this._DisplayNameID;
			}
			set
			{
				if ((this._DisplayNameID != value))
				{
					this.OnDisplayNameIDChanging(value);
					this.SendPropertyChanging();
					this._DisplayNameID = value;
					this.SendPropertyChanged("DisplayNameID");
					this.OnDisplayNameIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEditable", DbType="Bit NOT NULL")]
		public bool IsEditable
		{
			get
			{
				return this._IsEditable;
			}
			set
			{
				if ((this._IsEditable != value))
				{
					this.OnIsEditableChanging(value);
					this.SendPropertyChanging();
					this._IsEditable = value;
					this.SendPropertyChanged("IsEditable");
					this.OnIsEditableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsViewable", DbType="Bit NOT NULL")]
		public bool IsViewable
		{
			get
			{
				return this._IsViewable;
			}
			set
			{
				if ((this._IsViewable != value))
				{
					this.OnIsViewableChanging(value);
					this.SendPropertyChanging();
					this._IsViewable = value;
					this.SendPropertyChanged("IsViewable");
					this.OnIsViewableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentID", DbType="BigInt")]
		public System.Nullable<long> CommentID
		{
			get
			{
				return this._CommentID;
			}
			set
			{
				if ((this._CommentID != value))
				{
					this.OnCommentIDChanging(value);
					this.SendPropertyChanging();
					this._CommentID = value;
					this.SendPropertyChanged("CommentID");
					this.OnCommentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDownloadable", DbType="Bit NOT NULL")]
		public bool IsDownloadable
		{
			get
			{
				return this._IsDownloadable;
			}
			set
			{
				if ((this._IsDownloadable != value))
				{
					this.OnIsDownloadableChanging(value);
					this.SendPropertyChanging();
					this._IsDownloadable = value;
					this.SendPropertyChanged("IsDownloadable");
					this.OnIsDownloadableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HierStrucID", DbType="BigInt NOT NULL")]
		public long HierStrucID
		{
			get
			{
				return this._HierStrucID;
			}
			set
			{
				if ((this._HierStrucID != value))
				{
					this.OnHierStrucIDChanging(value);
					this.SendPropertyChanging();
					this._HierStrucID = value;
					this.SendPropertyChanged("HierStrucID");
					this.OnHierStrucIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectNumber", DbType="Int")]
		public System.Nullable<int> ObjectNumber
		{
			get
			{
				return this._ObjectNumber;
			}
			set
			{
				if ((this._ObjectNumber != value))
				{
					this.OnObjectNumberChanging(value);
					this.SendPropertyChanging();
					this._ObjectNumber = value;
					this.SendPropertyChanged("ObjectNumber");
					this.OnObjectNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPLICATIONTYPE", DbType="NVarChar(25)")]
		public string APPLICATIONTYPE
		{
			get
			{
				return this._APPLICATIONTYPE;
			}
			set
			{
				if ((this._APPLICATIONTYPE != value))
				{
					this.OnAPPLICATIONTYPEChanging(value);
					this.SendPropertyChanging();
					this._APPLICATIONTYPE = value;
					this.SendPropertyChanged("APPLICATIONTYPE");
					this.OnAPPLICATIONTYPEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MENU_ITEM_MASTER")]
	public partial class MENU_ITEM_MASTER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MenuItemMasterID;
		
		private long _HierStrucID;
		
		private System.Nullable<int> _ObjectNumber;
		
		private long _NameID;
		
		private System.Nullable<int> _ReportGroup;
		
		private string _Status;
		
		private System.Nullable<int> _RecipeLinkID;
		
		private bool _IsVisible;
		
		private bool _IsDeleted;
		
		private System.Nullable<System.DateTime> _MenuItemMasterPostingTime;
		
		private string _TempConfiguration;
		
		private System.Nullable<int> _FamGrpObjNum;
		
		private System.Nullable<int> _MajGrpObjNum;
		
		private System.Nullable<int> _MasterGrpObjNum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuItemMasterIDChanging(int value);
    partial void OnMenuItemMasterIDChanged();
    partial void OnHierStrucIDChanging(long value);
    partial void OnHierStrucIDChanged();
    partial void OnObjectNumberChanging(System.Nullable<int> value);
    partial void OnObjectNumberChanged();
    partial void OnNameIDChanging(long value);
    partial void OnNameIDChanged();
    partial void OnReportGroupChanging(System.Nullable<int> value);
    partial void OnReportGroupChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnRecipeLinkIDChanging(System.Nullable<int> value);
    partial void OnRecipeLinkIDChanged();
    partial void OnIsVisibleChanging(bool value);
    partial void OnIsVisibleChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnMenuItemMasterPostingTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnMenuItemMasterPostingTimeChanged();
    partial void OnTempConfigurationChanging(string value);
    partial void OnTempConfigurationChanged();
    partial void OnFamGrpObjNumChanging(System.Nullable<int> value);
    partial void OnFamGrpObjNumChanged();
    partial void OnMajGrpObjNumChanging(System.Nullable<int> value);
    partial void OnMajGrpObjNumChanged();
    partial void OnMasterGrpObjNumChanging(System.Nullable<int> value);
    partial void OnMasterGrpObjNumChanged();
    #endregion
		
		public MENU_ITEM_MASTER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemMasterID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MenuItemMasterID
		{
			get
			{
				return this._MenuItemMasterID;
			}
			set
			{
				if ((this._MenuItemMasterID != value))
				{
					this.OnMenuItemMasterIDChanging(value);
					this.SendPropertyChanging();
					this._MenuItemMasterID = value;
					this.SendPropertyChanged("MenuItemMasterID");
					this.OnMenuItemMasterIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HierStrucID", DbType="BigInt NOT NULL")]
		public long HierStrucID
		{
			get
			{
				return this._HierStrucID;
			}
			set
			{
				if ((this._HierStrucID != value))
				{
					this.OnHierStrucIDChanging(value);
					this.SendPropertyChanging();
					this._HierStrucID = value;
					this.SendPropertyChanged("HierStrucID");
					this.OnHierStrucIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectNumber", DbType="Int")]
		public System.Nullable<int> ObjectNumber
		{
			get
			{
				return this._ObjectNumber;
			}
			set
			{
				if ((this._ObjectNumber != value))
				{
					this.OnObjectNumberChanging(value);
					this.SendPropertyChanging();
					this._ObjectNumber = value;
					this.SendPropertyChanged("ObjectNumber");
					this.OnObjectNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameID", DbType="BigInt NOT NULL")]
		public long NameID
		{
			get
			{
				return this._NameID;
			}
			set
			{
				if ((this._NameID != value))
				{
					this.OnNameIDChanging(value);
					this.SendPropertyChanging();
					this._NameID = value;
					this.SendPropertyChanged("NameID");
					this.OnNameIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportGroup", DbType="Int")]
		public System.Nullable<int> ReportGroup
		{
			get
			{
				return this._ReportGroup;
			}
			set
			{
				if ((this._ReportGroup != value))
				{
					this.OnReportGroupChanging(value);
					this.SendPropertyChanging();
					this._ReportGroup = value;
					this.SendPropertyChanged("ReportGroup");
					this.OnReportGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipeLinkID", DbType="Int")]
		public System.Nullable<int> RecipeLinkID
		{
			get
			{
				return this._RecipeLinkID;
			}
			set
			{
				if ((this._RecipeLinkID != value))
				{
					this.OnRecipeLinkIDChanging(value);
					this.SendPropertyChanging();
					this._RecipeLinkID = value;
					this.SendPropertyChanged("RecipeLinkID");
					this.OnRecipeLinkIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisible", DbType="Bit NOT NULL")]
		public bool IsVisible
		{
			get
			{
				return this._IsVisible;
			}
			set
			{
				if ((this._IsVisible != value))
				{
					this.OnIsVisibleChanging(value);
					this.SendPropertyChanging();
					this._IsVisible = value;
					this.SendPropertyChanged("IsVisible");
					this.OnIsVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemMasterPostingTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> MenuItemMasterPostingTime
		{
			get
			{
				return this._MenuItemMasterPostingTime;
			}
			set
			{
				if ((this._MenuItemMasterPostingTime != value))
				{
					this.OnMenuItemMasterPostingTimeChanging(value);
					this.SendPropertyChanging();
					this._MenuItemMasterPostingTime = value;
					this.SendPropertyChanged("MenuItemMasterPostingTime");
					this.OnMenuItemMasterPostingTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TempConfiguration", DbType="NVarChar(MAX)")]
		public string TempConfiguration
		{
			get
			{
				return this._TempConfiguration;
			}
			set
			{
				if ((this._TempConfiguration != value))
				{
					this.OnTempConfigurationChanging(value);
					this.SendPropertyChanging();
					this._TempConfiguration = value;
					this.SendPropertyChanged("TempConfiguration");
					this.OnTempConfigurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamGrpObjNum", DbType="Int")]
		public System.Nullable<int> FamGrpObjNum
		{
			get
			{
				return this._FamGrpObjNum;
			}
			set
			{
				if ((this._FamGrpObjNum != value))
				{
					this.OnFamGrpObjNumChanging(value);
					this.SendPropertyChanging();
					this._FamGrpObjNum = value;
					this.SendPropertyChanged("FamGrpObjNum");
					this.OnFamGrpObjNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MajGrpObjNum", DbType="Int")]
		public System.Nullable<int> MajGrpObjNum
		{
			get
			{
				return this._MajGrpObjNum;
			}
			set
			{
				if ((this._MajGrpObjNum != value))
				{
					this.OnMajGrpObjNumChanging(value);
					this.SendPropertyChanging();
					this._MajGrpObjNum = value;
					this.SendPropertyChanged("MajGrpObjNum");
					this.OnMajGrpObjNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterGrpObjNum", DbType="Int")]
		public System.Nullable<int> MasterGrpObjNum
		{
			get
			{
				return this._MasterGrpObjNum;
			}
			set
			{
				if ((this._MasterGrpObjNum != value))
				{
					this.OnMasterGrpObjNumChanging(value);
					this.SendPropertyChanging();
					this._MasterGrpObjNum = value;
					this.SendPropertyChanged("MasterGrpObjNum");
					this.OnMasterGrpObjNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
